- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Upgrade packages.
      apt:
        upgrade: dist
        update_cache: yes
    - name: Install packages.
      apt: name={{item}}
      with_items:
      - ansible
      - git
      - vim

