- hosts: localhost
  connection: local
  tasks:
    - name: Upgrade packages.
      apt:
        upgrade: dist
        update_cache: yes
      become: true
    - name: Install packages.
      apt: name={{item}}
      become: true
      with_items:
      - ansible
      - git
      - vim
    - include: tasks/keybase.yml

