- hosts: localhost
  connection: local
  tasks:
    - name: Upgrade packages.
      apt:
        upgrade: dist
        update_cache: yes
      become: true
    - include: tasks/git.yml
    - include: tasks/keybase.yml
    - include: tasks/piavpn.yml
    - include: tasks/vim.yml

