- name: Add Docker GPG key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: true
- name: Add Docker repository.
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
  become: true
- name: Install Docker.
  apt:
    name: "{{ packages }}"
  become: true
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: Add user to the docker group.
  user:
    name: allenhair
    append: true
    groups: docker
  become: true

