- name: Install git.
  apt:
    name: git
  become: true
- name: Configure git.
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - {name: "core.editor", value: "vim"}
    - {name: "user.email", value: "allenhair@gmail.com"}
    - {name: "user.name", value: "Allen Hair"}

