- name: Check if keybase is installed.
  apt:
    name: keybase
    state: present
  check_mode: true
  register: keybase
- name: Install keybase.
  apt:
    deb: https://prerelease.keybase.io/keybase_amd64.deb
  become: true
  when: keybase.changed
- name: Start keybase.
  command: run_keybase
  when: keybase.changed

