" Define plugins. Use :PlugInstall to update.
runtime plugins.vim

" Configure vim-codefmt.
call glaive#Install()
Glaive codefmt google_java_executable=`expand('java -jar $HOME/.java/bin/google-java-format-1.9-all-deps.jar')`

" Enable solarized colorscheme.
set termguicolors
set background=dark
silent! colorscheme solarized8

" Use spaces instead of tabs.
set expandtab

" 1 tab = 2 spaces.
set shiftwidth=2
set softtabstop=2

" Highlight text matching current search.
set hlsearch

" Press space to clear highlighting.
nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>

